# Session 05

## Numpy

In [1]:
import numpy as np

In [2]:
# Python list
numbers_list = [1, 2, 3, 4, 5]
# NumPy array
numbers_array = np.array([1, 2, 3, 4, 5])

In [3]:
# 1 row x 5 columns - vector, 1d
vector = np.array([1, 2, 3, 4, 5])
# vector.ndim = 1 -> axes
# vector.shape = (5,1) -> size in each direction
# vector.size = 5 -> number of values

# 2 rows x 3 columns; matrix - 2d
matrix = np.array([[1, 2, 3],
[4, 5, 6]])
matrix
# matrix.ndim = 2, matrix.shape = (2,3), matrix.size = 6

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Placeholder arrays
np.zeros((2,3)) # all zeros

np.ones((2,3)) # all 1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# special numpy arrays

# NumPy array from 1 until 10 in steps of 2
np.arange(1,10,2)

# NumPy array of 5 random integers between 1 and 10
np.random.seed(1234) # makes the random set repeatable 
random_array = np.random.randint(1,10,5)
random_array2 = np.random.randint(1,10,5)
print(random_array)
print(random_array2)

# NumPy array of 10 repeated 5 times
np.repeat(10,5)

# NumPy array repeated x times
np.tile(vector, 2)

[4 7 6 5 9]
[2 8 7 9 1]


array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [21]:
# simulating data

# Create a Generator
rng = np.random.default_rng()

# 10 data points from normal distributed data with a mean of 0, sd 1
rng.normal(0,1,10)
# can also use uniform distribution, poisson etc

array([-0.35164186,  1.06387107, -0.28169781, -0.27477793,  0.71959381,
        0.07747421,  1.08618746,  0.19005109,  0.17528705, -0.85468298])

In [22]:
# reshaping arrays

# 2 rows x 3 columns
matrix = np.array([[1, 2, 3],[4, 5, 6]])

# 3 rows x 2 column
matrix.T # transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# collapse/flatten to 1d

# 2 rows x 3 columns
matrix = np.array([[1, 2, 3],[4, 5, 6]])
# 1 row x 6 columns
matrix.flatten()

In [23]:
# shared axes size, can be stacked together on that axes

matrix1 = np.array([[1, 2, 3],
[4, 5, 6]])
matrix2 = np.array([[7, 8, 9],
[10, 11, 12]])

print(np.vstack((matrix1,matrix2))) #vertical stack
print(np.hstack((matrix1,matrix2))) #horizontal stack



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [27]:
# apply operations to all values at once, without a loop

numbers_array = np.array([1, 2, 3, 4, 5])
numbers_array * 2
print(numbers_array)
# array([ 2, 4, 6, 8, 10])

# can perform operations when arrays are same length
matrix1 = np.array([[1, 2, 3],[4, 5, 6]])
matrix2 = np.array([[7, 8, 9],[10, 11, 12]])
matrix_sum = matrix2 - matrix1
print(matrix_sum)

# can summarize values
matrix1 = np.array([[1, 2, 3],[4, 5, 6]])
print(matrix1.sum()) #1 + 2 + 3 + 4 + 5 + 6 = 21
print(matrix1.max()) #6
print(matrix1.mean()) # 1 + 2 + 3 + 4 + 5 + 6 / 6 = 3.5

[1 2 3 4 5]
[[6 6 6]
 [6 6 6]]
21
6
3.5


## Multi-directional operations

In [28]:
matrix1 = np.array([[1, 2, 3],[4, 5, 6]])
matrix1.mean(axis=0)
matrix1.mean(axis=1)

array([2., 5.])

In [30]:
# index and slice arrays like a list
matrix1 = np.array([[1, 2, 3],[4, 5, 6]])
print(matrix1[0,:]) #first row
print(matrix[:,1]) #second column
print(matrix[1,1]) #second row, second column

[1 2 3]
[2 5]
5


In [32]:
# mutate or update elements; also, copy
matrix1 = np.array([[1, 2, 3],[4, 5, 6]])
matrix3 = matrix1.copy()
matrix3[1,1] = 50 #replace 5 with 50, original not changed
print(matrix3)
print(matrix1)

[[ 1  2  3]
 [ 4 50  6]]
[[1 2 3]
 [4 5 6]]


In [34]:
# check if all values share factor
print(matrix3 % 3 == 0)

# can filter with boolean expression as mask
matrix3[matrix3 % 3 == 0]

[[False False  True]
 [False False  True]]


array([3, 6])

In [36]:
# masks to generate new arrays with conditionals
np.where(matrix3 % 3 == 0, # condition
matrix3, # return the element if True
0) # return 0 if False
# array([[ 0, 0, 3], [ 0, 0, 6]])

array([[0, 0, 3],
       [0, 0, 6]])

## Exercises

In [41]:
# exercise 1
# 1d array of numbers 1 to 20
# compute sum, mean, standard dev of array
arr1 = np.arange(1,21,1)

print(arr1)
print(arr1.sum())
print(arr1.mean())
print(arr1.std())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
210
10.5
5.766281297335398


In [45]:
# exercise 2
arr2 = np.array([[2,7,12],[4,15,3],[8,1,20]])

# select all elements > 10
print(
    arr2[arr2 > 10]
)

# replace all elements < 5 with 0
print(np.where(arr2 < 5, 0, arr2))

[12 15 20]
[[ 0  7 12]
 [ 0 15  0]
 [ 8  0 20]]


In [53]:
# exercise 3
arr3 = np.array([[2, 7, 12],
    [4, 15, 3],
    [8, 1, 20]])

# print col 1
print(arr3[:,0])

# print last row
print(arr3[-1:])

# print element in r 2nd, c 3rd
print(arr3[1,2])

[2 4 8]
[[ 8  1 20]]
3


In [58]:
# Exercise 4
arr4 = np.array([[2, 7, 12],
    [4, 15, 3],
    [8, 1, 20]])

# sum of each column
print(arr4.sum(axis=0))

# mean of each row
print(arr4.mean(axis=1))

[14 23 35]
[7.         7.33333333 9.66666667]
